name: RustEdit Downloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PatchKit Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          curl -sSL https://raw.githubusercontent.com/patchkit-net/patchkit-tools/master/install.sh | bash
          echo "$HOME/.patchkit-tools/bin" >> $GITHUB_PATH

      - name: Get Version Label
        id: version_info
        run: |
          VERSION_DATA=$(curl -s https://api2.patchkit.net/1/apps/17ad1bce388b0f0a7566b8a8597c53d6/versions/latest)
          LABEL=$(echo $VERSION_DATA | grep -oP '"label":"\K[^"]+')
          echo "VERSION_LABEL=$LABEL" >> $GITHUB_OUTPUT
          echo "Последняя версия: $LABEL"

      - name: Download RustEdit
        run: |
          mkdir rustedit_full
          patchkit-tools download-app --secret 17ad1bce388b0f0a7566b8a8597c53d6 --output rustedit_full/ --force

      - name: Create ZIP
        run: |
          zip -r RustEdit_v${{ steps.version_info.outputs.VERSION_LABEL }}.zip rustedit_full/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RustEdit_v${{ steps.version_info.outputs.VERSION_LABEL }}
          path: RustEdit_v${{ steps.version_info.outputs.VERSION_LABEL }}.zip
